---

- name: "configuration play." 
  hosts: web
  user: ubuntu
  become: yes
  become_method: sudo
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml

  environment:
    ENVIRONMENT: Production
    TYPEORM_CONNECTION: postgres
    TYPEORM_ENTITIES: ./src/modules/domain/**/*.entity.ts
    TYPEORM_HOST: udapeople-prod.cppkkrp6zc4w.us-west-2.rds.amazonaws.com
    TYPEORM_PORT: 5432
    TYPEORM_USERNAME: postgres
    TYPEORM_PASSWORD: test1234
    TYPEORM_DATABASE: postgres

  pre_tasks:
    - name: Wait 600 seconds for target connection to become reachable/usable
      wait_for_connection:
        delay: 60
        timeout: 300
  
  roles:
    - configure-server
