---
    
- name: "Install node version 14.x"
  shell: |
    sudo apt update
    curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
    sudo apt-get install -y nodejs

- name: "install pm2"
  become: yes
  become_method: sudo
  npm:
    name: pm2
    global: yes
    production: yes
    state: present
