---

  environment:
    ENVIRONMENT: Production
    TYPEORM_CONNECTION: postgres
    TYPEORM_ENTITIES: ./src/modules/domain/**/*.entity.ts
    TYPEORM_HOST: udapeople-prod.cppkkrp6zc4w.us-west-2.rds.amazonaws.com
    TYPEORM_PORT: 5432
    TYPEORM_USERNAME: postgres
    TYPEORM_PASSWORD: test1234
    TYPEORM_DATABASE: postgres
     
- name: "update apt packages."
  become: yes
  become_method: sudo
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  become_method: sudo
  apt:
    upgrade: yes

- name: remove dependencies that are no longer required
  become: yes
  become_method: sudo
  apt:
    autoremove: yes

- name: "install dependencies."
  become: yes
  become_method: sudo
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: yes
  become_method: sudo
  npm:
    name: pm2
    global: yes
    production: yes
    state: present
