---
    
- name: "update apt packages."
  become: yes
  become_method: sudo
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  become_method: sudo
  apt:
    upgrade: yes

- name: remove dependencies that are no longer required
  become: yes
  become_method: sudo
  apt:
    autoremove: yes

- name: "install dependencies."
  become: yes
  become_method: sudo
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: yes
  become_method: sudo
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: "update apt packages."
  become: yes
  become_method: sudo
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  become_method: sudo
  apt:
    upgrade: yes
