---
    
- name: "update apt packages."
  become: yes
  become_method: sudo
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  become_method: sudo
  apt:
    upgrade: yes

- name: remove dependencies that are no longer required
  become: yes
  become_method: sudo
  apt:
    autoremove: yes

- name: "install dependencies."
  become: yes
  become_method: sudo
  apt:
    name: ["npm"]
    state: latest
    update_cache: yes

- name: "install n"
  become: yes
  npm:
    name: n
    global: yes
    production: yes

- name: "Install node version 13.x"
  shell: |
    curl -sL https://rpm.nodesource.com/setup_13.x | sudo -E bash -
    sudo apt install -y nodejs

- name: "install pm2"
  become: yes
  become_method: sudo
  npm:
    name: pm2
    global: yes
    production: yes
    state: present
