---
- name: "update apt packages"
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: "yes"

- name: "remove dependencies that are no longer required"
  become: yes
  apt:
    autoremove: yes
      
- name: "copy distribution zip"
  become: true
  copy:
    src: backend_artifact.tar.gz
    dest: backend_artifact.tar.gz

- name: "Unpack dist files"
  become: true
  shell: |
    tar -xzf backend_artifact.tar.gz
    rm backend_artifact.tar.gz

#- name: "copy distribution zip"
#  become: true
#  copy:
#    src: test.tar.gz
#    dest: test.tar.gz

#- name: "Unpack dist files"
#  become: true
#  shell: |
#    tar -xzf test.tar.gz
#    rm test.tar.gz

- name: "copy distribution zip"
  become: true
  copy:
    src: .env
    dest: dist/.env
    
- name: Executing node
  become: true
  shell: |
    export ENVIRONMENT=production
    export NODE_ENV=production
    export TYPEORM_CONNECTION=postgres
    export TYPEORM_ENTITIES=./modules/domain/*/*/*.entity.js
    export TYPEORM_HOST=udapeople-prod.cppkkrp6zc4w.us-west-2.rds.amazonaws.com
    export TYPEORM_PORT=5432
    export TYPEORM_USERNAME=postgres
    export TYPEORM_PASSWORD=test1234
    export TYPEORM_DATABASE=postgres
    node dist/main.js
