---
- name: "update apt packages"
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: "yes"

- name: "remove dependencies that are no longer required"
  become: yes
  apt:
    autoremove: yes

- name: "Check if distribution zip is available"
  become: true
  shell: |
    ls -lrt 
    
- name: "copy distribution zip"
  become: true
  copy:
    src: backend_artifact.tar.gz
    dest: backend_artifact.tar.gz

- name: "Unpack dist files"
  become: true
  shell: |
    tar -xzf backend_artifact.tar.gz
    rm backend_artifact.tar.gz

- name: Executing node
  become: true
  shell: |
    node dist/main.js
