---
- name: "update apt packages"
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: "yes"

- name: "remove dependencies that are no longer required"
  become: yes
  apt:
    autoremove: yes
      
- name: "copy distribution zip"
  become: true
  copy:
    src: backend_artifact.tar.gz
    dest: backend_artifact.tar.gz

- name: "Unpack dist files"
  become: true
  shell: |
    tar -xzf backend_artifact.tar.gz
    rm backend_artifact.tar.gz

#- name: "copy distribution zip"
#  become: true
#  copy:
#    src: test.tar.gz
#    dest: test.tar.gz

#- name: "Unpack dist files"
#  become: true
#  shell: |
#    tar -xzf test.tar.gz
#    rm test.tar.gz

- name: "copy distribution zip"
  become: true
  copy:
    src: .env
    dest: dist/.env
    
- name: Executing node
  become: true
  shell: |
    sh dist/.env
    node dist/main.js
