version: 2.1

commands:
  destroy-environment:
    description: Destroy back-end and front-end cloudformation stacks given a workflow ID.
    parameters:
      backend-stack:
        description: backend stack name
        type: string
        default: udapeople-backendstack-${CIRCLE_WORKFLOW_ID}
      frontend-stack:
        description: frontend stack name
        type: string
        default: udapeople-frontendstack-${CIRCLE_WORKFLOW_ID}
      bucket-name:
        description: frontend S3 bucket name
        type: string
        default: udapeople-"${CIRCLE_WORKFLOW_ID}"
    steps:
      - run:
          name: Destroy environments
          when: on_fail
          command: |
            aws cloudformation delete-stack --stack-name << parameters.frontend-stack >>
            aws cloudformation delete-stack --stack-name << parameters.backend-stack >>
            aws s3 rm s3://<< parameters.bucket-name >> --recursive

  revert-migrations:
    description: Revert the last migration if successfully run in the current workflow.
    parameters:
      memstash-token:
        description: Memstash token for migration result
        type: string
        default: "token:migration_${CIRCLE_WORKFLOW_ID}"     
    steps:
      - run:
          name: Revert migrations
          when: on_fail 
          command: |
            SUCCESS=$(curl -H "Content-Type: text/plain" -H << parameters.memstash-token >> --request GET https://api.memstash.io/values/migrationStatus)
            if [ $SUCCESS==1 ] 
            then
              cd ~/project/backend
              npm install
              npm migrations:revert
            fi
     
 
jobs:
  build-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [build-frontend]
      - run:
          name: Build front-end
          command: |
            cd frontend
            npm i
            npm run build
      - save_cache:
          paths: [frontend/node_modules]
          key: build-frontend

  build-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [build-backend]
      - run:
          name: Back-end build
          command: |
            cd backend
            npm i
            npm run build --prod
            cd dist
            ls -lrt
      - save_cache:
          paths: [backend/node_modules]
          key: build-backend 
          
  test-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [build-frontend]
      - run:
          name: Front-end test cases
          command: |
            cd frontend
            npm install jest
            npm run test   
            
  test-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [build-backend]
      - run:
          name: Backend-end test cases
          command: |
            cd backend
            npm run test
            
  scan-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [build-frontend]
      - run:
          name: Frontend vulnerability scan
          command: |
            cd frontend
            npm audit fix --audit-level=critical --force
  scan-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [build-backend]
      - run:
          name: Backend vulnerability scan
          command: |
            cd backend
            npm audit fix --audit-level=critical --force
            
  deploy-infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Ensure back-end infrastructure exists
          command: |
            aws cloudformation deploy \
              --template-file .circleci/files/backend.yml \
              --tags project=udapeople \
              --stack-name udapeople-backendstack-${CIRCLE_WORKFLOW_ID} \
              --parameter-overrides ID=${CIRCLE_WORKFLOW_ID}
              
      - run:
          name: Ensure front-end infrastructure exist
          command: |
            aws cloudformation deploy \
              --template-file .circleci/files/frontend.yml \
              --tags project=udapeople \
              --stack-name udapeople-frontendstack-${CIRCLE_WORKFLOW_ID} \
              --parameter-overrides ID=${CIRCLE_WORKFLOW_ID}
                  
  create_inventory:
    working_directory: ~/project
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout 
      - run:
          name: Install dependencies
          command: |
            yum install -y tar gzip     
      - run:
          name: Add back-end ip to ansible inventory and upload dnsname to memstash
          command: |
             echo "[web]" > .circleci/ansible/inventory.txt
             aws ec2 describe-instances \
               --filter Name=tag:aws:cloudformation:stack-name,Values=udapeople-backendstack* Name=instance-state-name,Values=running \
               --query 'Reservations[*].Instances[*].PublicIpAddress' \
               --output text >> .circleci/ansible/inventory.txt

             dnsname=$(aws ec2 describe-instances --filter Name=tag:aws:cloudformation:stack-name,Values=udapeople-backendstack* Name=instance-state-name,Values=running --query 'Reservations[*].Instances[*].PublicDnsName' --output text)
             curl -H "Content-Type: text/plain" -H "token: API_URL-${CIRCLE_WORKFLOW_ID}" --request PUT --data ${dnsname} https://api.memstash.io/values/dnsname               
  
      - persist_to_workspace:
          root: ~/project
          paths: 
            - .circleci/ansible/inventory.txt
      - destroy-environment
            
  check_inventory:
    working_directory: ~/project
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout            
      - attach_workspace:
          at: ~/project
      - run:
          name: Check inventory file exists
          command: |
            cat ./.circleci/ansible/inventory.txt
      - destroy-environment
  
  configure_infrastructure:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ["fb:92:3b:fa:49:6c:96:aa:dd:78:39:3d:d9:a7:75:92"]
      - attach_workspace:
          at: ~/project
      - run:
          name: Install dependencies
          command: |
            apk add --update ansible
            apk -Uuv add groff less python py-pip
            pip install awscli
            
      - run:
          name: List files under Ansible Directory
          command: |
            cd .circleci/ansible
            ls -lrt            
      - run:
          name: Configure server
          command: |
            cd .circleci/ansible
            ansible-playbook -i inventory.txt  configure-server.yml
      - run:
          name: Configure node-exporter
          command: |
            cd .circleci/ansible
            ansible-playbook -i inventory.txt  configure-prometheus-node-exporter.yml
      - destroy-environment

            
  run_migrations:
    docker:
      - image: circleci/node:13.8.0
    environment:
      migration_status: 0
    steps:
      - checkout
      - restore_cache:
          keys: [build-backend]
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update
            sudo apt-get install awscli
      - run:
          name: Run migrations
          command: |
            cd backend
            npm run migrations > output.log
            migration_status=`grep -c "has been executed successfully"  output.log`
            cat output.log
            echo $migration_status
            if [[ $migration_status -eq 0 ]]  
            then
              cat /home/circleci/.npm/_logs/*.log
              npm run migrations:revert
              curl -H "Content-Type: text/plain" -H "token: migration-${CIRCLE_WORKFLOW_ID}" --request PUT --data "$migration_status" https://api.memstash.io/values/migrationStatus
            else  
              migration_status=1
              curl -H "Content-Type: text/plain" -H "token: migration-${CIRCLE_WORKFLOW_ID}" --request PUT --data "$migration_status" https://api.memstash.io/values/migrationStatus
            fi
      - destroy-environment
  
  deploy-frontend:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            yum install -y tar gzip
            curl -sL https://rpm.nodesource.com/setup_13.x | bash -
            yum install -y nodejs 
      - attach_workspace:
          at: ~/project
      - run:
          name: Get API_URL
          command: |
            DNSNAME=$(curl -H "token: API_URL-${CIRCLE_WORKFLOW_ID}" --request GET https://api.memstash.io/values/dnsname)
            API_URL="http://${DNSNAME}:3030"
            curl -H "Content-Type: text/plain" -H "token:API_URL_${CIRCLE_WORKFLOW_ID}" --request PUT --data "$API_URL" https://api.memstash.io/values/API_URL
            export API_URL="http://${DNSNAME}:3030"
            echo "API_URL=${API_URL}" >> ~/project/frontend/.env
            echo "NODE_ENV=production" >> ~/project/frontend/.env
            echo "ENVIRONMENT=production" >>  ~/project/frontend/.env
            cat ~/project/frontend/.env
            echo "API_URL=${API_URL}"
            cd ~/project/frontend
            npm install
            npm run build
            cd dist
            ls -lrt
            aws s3 sync . s3://udapeople-"${CIRCLE_WORKFLOW_ID}" --delete

      - destroy-environment         
      - revert-migrations

  deploy-backend:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ["fb:92:3b:fa:49:6c:96:aa:dd:78:39:3d:d9:a7:75:92"]
      - attach_workspace:
          at: ~/project
      - run:
          name: Install dependencies
          command: |
            apk add --update ansible tar gzip nodejs npm curl
            apk -Uuv add groff less python py-pip
            pip install awscli            
      - run:
          name: Deploy backend
          command: |
            cd backend
            npm install
            npm run build
            
            cp -r node_modules dist/
            tar -czvf backend_artifact.tar.gz dist
            
            cd ..
            mv backend/backend_artifact.tar.gz .circleci/ansible/roles/deploy/files
            cd .circleci/ansible/roles/deploy/files
            ansible-playbook -i ~/project/.circleci/ansible/inventory.txt ~/project/.circleci/ansible/deploy-backend.yml -vvv
      - destroy-environment         
      - revert-migrations

  smoke-test:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [build-backend]
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update
            sudo apt-get install awscli
            sudo apt install curl
      - run:
          name: Smoke test for frontend
          command: |
            export URL="http://udapeople-${CIRCLE_WORKFLOW_ID}.s3-website-us-west-2.amazonaws.com"
            echo "Frontend URL: $URL"
            if [[ $(curl -s ${URL} | grep  "Welcome") ]]
            then
              exit 0
            else
              exit 1
            fi
      - run:
          name: Get backend url and run smoke test
          command: |
            export API_URL=$(curl -H "Content-Type: text/plain" -H "token:API_URL_${CIRCLE_WORKFLOW_ID}" --request GET https://api.memstash.io/values/API_URL)
            echo "Backend API_URL: $API_URL"
            if curl -s $API_URL > curl_backend_output.txt
            then
              exit 0
            else
              exit 0
            fi
      - destroy-environment         
      - revert-migrations
  
  cloudfront-update:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Update cloudfront distribution
          command: |
            export OldWorkflowID=$(aws cloudformation \
            list-exports --query 'Exports[?Name==`WorkflowID`].Value' \
            --no-paginate --output text)
            
            export STACKS=($aws cloudformation list-stacks --query "StackSummaries[*].StackName" \
            --stack-status-filter CREATE_COMPLETE --no-paginate)
            
            echo Old Workflow Id: "${OldWorkflowID}"

            aws cloudformation deploy \
            --template-file .circleci/files/cloudfront.yml \
            --stack-name=udapeople-cloudfront \
            --parameter-overrides WorkflowID="${CIRCLE_WORKFLOW_ID}" \
            --tags project=udapeople 

            if [[ "${STACKS[@]}" =~ "${OldWorkflowID}" ]]
            then
              aws s3 rm "s3://udapeople-${OldWorkflowID}" --recursive
              aws cloudformation delete-stack --stack-name "udapeople-backendstack-${OldWorkflowID}"
              aws cloudformation delete-stack --stack-name "udapeople-frontendstack-${OldWorkflowID}"
            fi
          
workflows:
  default:
    jobs:
      - build-frontend
      - build-backend:
          requires: [build-frontend]
      - test-frontend:
          requires: [build-frontend]
      - test-backend:
          requires: [build-backend]
      - scan-backend:
          requires: [build-backend]
      - scan-frontend:
          requires: [build-frontend]
      - deploy-infrastructure:
          requires: [test-frontend, test-backend, scan-frontend, scan-backend]
          filters:
            branches:
              only: [main]
      - create_inventory:
          requires: [deploy-infrastructure]
      - check_inventory:
          requires: [create_inventory]
      - configure_infrastructure:
          requires: [check_inventory]
      - run_migrations:
          requires: [configure_infrastructure]
      - deploy-frontend:
          requires: [run_migrations]
      - deploy-backend:
          requires: [run_migrations]
      - smoke-test:
          requires: [deploy-frontend, deploy-backend]
      - cloudfront-update:
          requires: [smoke-test]
